# Generated by Django 5.2.12 on 2026-04-13 17:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osolot_server', '0002_collective_membership_collective_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='applied_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='membership',
            name='joined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['collective', 'user'], name='osolot_serv_collect_e7ce54_idx'),
        ),
    ]
