# Generated by Django 5.2.12 on 2026-04-17 19:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('osolot_server', '0004_membership_approved_by_alter_collective_members'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterField(
            model_name='collective',
            name='admission_type',
            field=models.CharField(choices=[('open', 'Open'), ('application', 'Application')], default='open'),
        ),
        migrations.AlterField(
            model_name='collective',
            name='description',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='collective',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits, and _.- only.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Username must be 3 to 31 characters: letters, digits, or _.-', regex='^[\\w.-]{3,31}\\Z')], verbose_name='username'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('email__contains', '@')), name='valid_email_must_contain_at'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('username__contains', '@'), _negated=True), name='valid_username_must_not_contain_at'),
        ),
    ]
