# Generated by Django 5.2.12 on 2026-04-23 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osolot_server', '0009_alter_collective_visibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('share_with_new_collectives_default', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('offer', 'Offer'), ('request', 'Request')], default='offer', max_length=31)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='membership',
            name='shared_posts',
            field=models.ManyToManyField(related_name='memberships_shared_with', to='osolot_server.post'),
        ),
    ]
