# Generated by Django 5.2.12 on 2026-04-27 18:57

import osolot_server.models.post
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osolot_server', '0011_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='shared_posts',
        ),
        migrations.AddField(
            model_name='post',
            name='shared_memberships',
            field=models.ManyToManyField(related_name='shared_posts', to='osolot_server.membership'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=osolot_server.models.post.generate_post_slug, max_length=16, unique=True),
        ),
    ]
