# Generated by Django 5.2.12 on 2026-04-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osolot_server', '0012_remove_membership_shared_posts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
