/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Osolot API
 * API for managing decentralized libraries of things.
 * OpenAPI spec version: 0.0.1
 */
import { customInstance } from './axios-instance';
export type UserUpdateInName = string | null;

export interface UserUpdateIn {
  name?: UserUpdateInName;
}

export interface UserOut {
  email: string;
  id: number;
  name: string;
  username: string;
}

export interface RefreshIn {
  refresh: string;
}

export interface AccessTokenOut {
  access: string;
}

export interface LoginIn {
  password: string;
  username: string;
}

export type RegisterInEmail = string | null;

export interface RegisterIn {
  email?: RegisterInEmail;
  /** @maxLength 255 */
  name?: string;
  /** @minLength 8 */
  password: string;
  /**
   * @minLength 1
   * @maxLength 150
   */
  username: string;
}

export interface TokenPairOut {
  access: string;
  refresh: string;
}





  export const getOsolotAPI = () => {
/**
 * @summary Register
 */
const osolotServerRoutesRegister = (
    registerIn: RegisterIn,
 ) => {
      return customInstance<TokenPairOut>(
      {url: `/api/auth/register`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: registerIn
    },
      );
    }
  
/**
 * @summary Login
 */
const osolotServerRoutesLogin = (
    loginIn: LoginIn,
 ) => {
      return customInstance<TokenPairOut>(
      {url: `/api/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginIn
    },
      );
    }
  
/**
 * @summary Refresh
 */
const osolotServerRoutesRefresh = (
    refreshIn: RefreshIn,
 ) => {
      return customInstance<AccessTokenOut>(
      {url: `/api/auth/refresh`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: refreshIn
    },
      );
    }
  
/**
 * @summary Me
 */
const osolotServerRoutesMe = (
    
 ) => {
      return customInstance<UserOut>(
      {url: `/api/users/me`, method: 'GET'
    },
      );
    }
  
/**
 * @summary Update Me
 */
const osolotServerRoutesUpdateMe = (
    userUpdateIn: UserUpdateIn,
 ) => {
      return customInstance<UserOut>(
      {url: `/api/users/me`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: userUpdateIn
    },
      );
    }
  
return {osolotServerRoutesRegister,osolotServerRoutesLogin,osolotServerRoutesRefresh,osolotServerRoutesMe,osolotServerRoutesUpdateMe}};
export type OsolotServerRoutesRegisterResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOsolotAPI>['osolotServerRoutesRegister']>>>
export type OsolotServerRoutesLoginResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOsolotAPI>['osolotServerRoutesLogin']>>>
export type OsolotServerRoutesRefreshResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOsolotAPI>['osolotServerRoutesRefresh']>>>
export type OsolotServerRoutesMeResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOsolotAPI>['osolotServerRoutesMe']>>>
export type OsolotServerRoutesUpdateMeResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOsolotAPI>['osolotServerRoutesUpdateMe']>>>
