/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Osolot API
 * Account and profile endpoints (JWT).
 * OpenAPI spec version: 1.0.0
 */
import { customInstance } from './axios-instance';
export type UserUpdateInName = string | null;

export interface UserUpdateIn {
  name?: UserUpdateInName;
}

export interface UserOut {
  email: string;
  id: number;
  name: string;
  username: string;
}

export interface RefreshIn {
  refresh: string;
}

export interface AccessTokenOut {
  access: string;
}

export interface LoginIn {
  password: string;
  username: string;
}

export type RegisterInEmail = string | null;

export interface RegisterIn {
  email?: RegisterInEmail;
  /** @maxLength 255 */
  name?: string;
  /** @minLength 8 */
  password: string;
  /**
   * @minLength 1
   * @maxLength 150
   */
  username: string;
}

export interface TokenPairOut {
  access: string;
  refresh: string;
}





  export const getOsolotAPI = () => {
/**
 * @summary Register
 */
const usersRoutesRegister = (
    registerIn: RegisterIn,
 ) => {
      return customInstance<TokenPairOut>(
      {url: `/api/auth/register`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: registerIn
    },
      );
    }
  
/**
 * @summary Login
 */
const usersRoutesLogin = (
    loginIn: LoginIn,
 ) => {
      return customInstance<TokenPairOut>(
      {url: `/api/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginIn
    },
      );
    }
  
/**
 * @summary Refresh
 */
const usersRoutesRefresh = (
    refreshIn: RefreshIn,
 ) => {
      return customInstance<AccessTokenOut>(
      {url: `/api/auth/refresh`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: refreshIn
    },
      );
    }
  
/**
 * @summary Me
 */
const usersRoutesMe = (
    
 ) => {
      return customInstance<UserOut>(
      {url: `/api/users/me`, method: 'GET'
    },
      );
    }
  
/**
 * @summary Update Me
 */
const usersRoutesUpdateMe = (
    userUpdateIn: UserUpdateIn,
 ) => {
      return customInstance<UserOut>(
      {url: `/api/users/me`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: userUpdateIn
    },
      );
    }
  
return {usersRoutesRegister,usersRoutesLogin,usersRoutesRefresh,usersRoutesMe,usersRoutesUpdateMe}};
export type UsersRoutesRegisterResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOsolotAPI>['usersRoutesRegister']>>>
export type UsersRoutesLoginResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOsolotAPI>['usersRoutesLogin']>>>
export type UsersRoutesRefreshResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOsolotAPI>['usersRoutesRefresh']>>>
export type UsersRoutesMeResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOsolotAPI>['usersRoutesMe']>>>
export type UsersRoutesUpdateMeResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getOsolotAPI>['usersRoutesUpdateMe']>>>
