import { Platform, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  flex: { flex: 1, backgroundColor: "#f6f7f9" },
  scrollContent: { padding: 16, paddingBottom: 32, gap: 12 },
  centered: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#f6f7f9",
  },
  card: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 16,
    gap: 8,
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 12,
    elevation: 2,
  },
  title: { fontSize: 22, fontWeight: "600" },
  subtitle: { fontSize: 16, fontWeight: "600", marginTop: 8 },
  label: { fontSize: 14, color: "#444", marginTop: 4 },
  hint: { fontSize: 14, color: "#555" },
  mono: {
    fontFamily: Platform.select({ ios: "Menlo", android: "monospace" }),
  },
  input: {
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 16,
  },
  inputMultiline: { minHeight: 80, textAlignVertical: "top" },
  button: {
    backgroundColor: "#111",
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: "center",
    marginTop: 8,
  },
  buttonDisabled: { opacity: 0.5 },
  buttonText: { color: "#fff", fontSize: 16, fontWeight: "600" },
  buttonSecondary: {
    borderWidth: 1,
    borderColor: "#ccc",
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: "center",
  },
  buttonSecondaryText: { fontSize: 16, color: "#111" },
  buttonDanger: {
    borderWidth: 1,
    borderColor: "#c00",
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: "center",
  },
  buttonDangerText: { fontSize: 16, color: "#c00" },
  linkButton: { paddingVertical: 8 },
  linkText: { color: "#3366cc", fontSize: 16 },
  row: { flexDirection: "row", alignItems: "center", gap: 8 },
  fab: {
    position: "absolute",
    right: 20,
    bottom: 20,
    backgroundColor: "#111",
    width: 56,
    height: 56,
    borderRadius: 28,
    alignItems: "center",
    justifyContent: "center",
    elevation: 4,
  },
  fabText: { color: "#fff", fontSize: 28, lineHeight: 32 },
  segmentRow: { flexDirection: "row", gap: 8, marginBottom: 8 },
  segment: {
    flex: 1,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#ccc",
    alignItems: "center",
  },
  segmentActive: { backgroundColor: "#111", borderColor: "#111" },
  segmentText: { fontSize: 14, color: "#111" },
  segmentTextActive: { color: "#fff" },
  badge: {
    fontSize: 12,
    color: "#555",
    backgroundColor: "#eee",
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 4,
    overflow: "hidden",
  },
  checkRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
  },
});
